post http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY3M2JmOGRkZmExMjYxYzNjMThlNWZlMSIsImlhdCI6MTczMTk4Mzk2Mn0.FiDcBVfzcp6TssTHA9Qceu8f3-P4Vh34iScpDzi2Aqk

{
    "content": "This is my authorizated note",
    "important": true
}