delete http://localhost:3001/api/blogs/673f5ba35d4875d5aa69467a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InFjYyIsImlkIjoiNjczZjUzZTczMDM3ZjJmZTlkNzMwZDFiIiwiaWF0IjoxNzMyMjAzODEwfQ.9FmFMAG2s4i5FRFVuP_NPIjkvTbKb_QRmlkvJrtOALQ